
#########################################################################
#
# Spliting and filtering the phyloseq object 
#
#########################################################################

setwd("c://Rprojects/Microbiota_MAP/")
dir.create("output/processing")
dir.create("output/processing/support_data")
library("phyloseq")
library("plyr")


# 0. Load generated by dada2_processing.R the phyloseq file. 
load(file = "output/dada2/phyloseq0.RData")

# 1. Split phyloseq into objects containing only
#          a) Samples of interest (ps0), 
#          b) Blanks (ps.b) 
#          c) Control Cows (ps.cc)

ps0 <- prune_samples(grepl("High|Low", ps@sam_data$Status), ps) 
ps.cc <- subset_samples(ps, Status=="ControlCows")
ps.b <- subset_samples(ps, Status=="Blank")

# 2. Filtering of the data 
# 2.1 Filter out reads that where not assign to any taxonomic level 

# 2.1.1 Check prevalence of OTUs in phylum 
# 2.1.1.1 Extract data about phylum prevalence 
prevdf <- apply(X = otu_table(ps0),
                MARGIN = ifelse(taxa_are_rows(ps0), yes=1, no=2),
                FUN = function(x){sum(x > 0)} )
#2.1.1.2 Convert into dataframe data about prevalance 
prevdf <- data.frame(Prevalence = prevdf,
                     TotalAbundance = taxa_sums(ps0), 
                     tax_table(ps0))
#2.1.1.3 Make the sammary table 
prev.s <- ddply(prevdf, "Phylum", function(df1){cbind(mean(df1$Prevalence), sum(df1$Prevalence))})

write.csv(prev.s, file = "output/processing/support_data/phylum_info.csv")

#2.1.1 Remove taxa that are not assigned to any phylum level 
ps1.1 <- subset_taxa(ps0, !is.na(Phylum))


#2.2 Remove taxa that were found in less than 3 samples 
filter.ps1.1<- ps1.1@otu_table
filter.ps1.1[filter.ps1.1 > 0 ] <- 1 
ps1.1 <- prune_taxa(colSums(filter.ps1.1) > 4, ps1.1)

# 2.2.1 Save resulted cleaned object 
saveRDS(ps1.1, "output/processing/ps1.1.rds")

rm(list = ls())
gc()

